const ObjectProject =
    [
        {
            id: 1,
            title: 'Social-network',
            img: 'https://camo.githubusercontent.com/0017c3567d89bd4c6da2941847c6ce70ff0666d9fad451734dffb4b8c4aaa8b8/68747470733a2f2f692e706f7374696d672e63632f537344776b34316e2f486f6d652d6578616d706c652e6a7067',
            description: 'Social Network App is a project carried out in node js in order to create a web app that is capable of fulfilling the functionalities of a social network...',
            demo: '',
            github: 'https://github.com/Fraineralex/Social-Network-App',
            authors: [{ name: "Luis Fernandez", githubA: "https://github.com/luisferllub230" }, { name: "Frainer Alexander", githubA: "https://github.com/Fraineralex" }, { name: "Alexander Echavarria", githubA: "https://github.com/Alexander2902" }],
            Classification: 'Express',
            technologies: ['HTML', 'CSS', 'Sass', 'Bootstrap', 'JavaScript', 'Nodejs', 'Express', 'Sqlite3', 'Sequelize'],
        },
        {
            id: 2,
            title: 'Periodic-Table',
            img: 'https://user-images.githubusercontent.com/84060723/177637222-f8eab23f-dac9-4e32-8033-5d3ed33f4376.png',
            description: 'this app displays the periodic table and its use server side rendering to display the table...',
            demo: 'https://periodic-table-lf.herokuapp.com/',
            github: 'https://github.com/luisferllub230/Periodic-Table#this-app-displays-the-periodic-table-and-its-use-server-side-rendering-to-display-the-table-if-one-of-the-elements-is-not-in-the-array-the-table-displays-a-box-with-a-404-text-and-change-the-box-background-for-a-gray-color',
            authors: [{name: "Luis Fernandez", githubA: "https://github.com/luisferllub230"}],
            Classification: 'Express',
            technologies: ['Html', 'CSS grip', 'Nodejs', 'Express'],
        },
        {
            id: 3,
            title: 'Pokedex',
            img: 'https://user-images.githubusercontent.com/84060723/190030784-7cbb38ee-ddd5-4140-b84f-32ec1d38801b.png',
            description: 'In this app you can create, see, edit and delete a pokemon information, regions and type of pokemon...',
            demo: '',
            github: 'https://github.com/luisferllub230/Pokedex/tree/main',
            authors: [{name: "Luis Fernandez", githubA: "https://github.com/luisferllub230"}],
            Classification: 'Express',
            technologies: ['Html', 'CSS', 'Nodejs', 'Express', 'handlebars', 'sequelize', 'mysql'],

        },
        {
            id: 4,
            title: 'My-portfolio',
            img: '',
            description: '...',
            demo: '',
            github: '',
            authors: [{name: "Luis Fernandez", githubA: "https://github.com/luisferllub230"}],
            Classification: 'React',
            technologies: ['Html', 'CSS', 'React', 'Bootstrap', 'framer motion'],
        },
        {
            id: 5,
            title: 'budget-manager',
            img: 'https://user-images.githubusercontent.com/84060723/189042218-7bdcd5be-6794-4b5a-8239-9d2fd229e38d.png',
            description: 'A simple budget-manager created in react...',
            demo: 'https://splendid-stardust-9b0405.netlify.app/',
            github: 'https://github.com/luisferllub230/budget-manager',
            authors: [{name: "Luis Fernandez", githubA: "https://github.com/luisferllub230"}],
            Classification: 'React',
            technologies: ['Html', 'CSS', 'React', 'Bootstrap'],
        },
        {
            id: 6,
            title: 'React-Cites',
            img: 'https://user-images.githubusercontent.com/84060723/188228074-ff0aa7e5-2b92-49e1-adcf-22769a9fa5cc.gif',
            description: 'react-cites is a gestor o cites create in react, you can register a pasient an se instantanialy your information...',
            demo: 'https://react-cites.netlify.app//',
            github: 'https://github.com/luisferllub230/react-cites',
            authors: [{name: "Luis Fernandez", githubA: "https://github.com/luisferllub230"}],
            Classification: 'React',
            technologies: ['Html', 'CSS', 'React', 'Bootstrap'],
        }
    ]

export default ObjectProject;